### ISSUE TITLE
Some bugs in latest main?

### ISSUE THREAD

**Issue by asitstands** [coady/multimethod#145]
I'm testing with the latest main (0d4bd1102f522cc75c18fcc1ea153ed4f1199f1c). It looks like the following are bugs.

```python
from dataclasses import dataclass
from typing import Any
from multimethod import multimethod

@dataclass
class Foo[T]:
    pass

@multimethod
def foo(x: Foo[Any]):
    pass

foo(Foo()) # foo(Foo[Any]()) works
```
```
AttributeError: 'Foo' object has no attribute '__orig_class__'. Did you mean: '__orig_bases__'?
```

```python
from multimethod import multimethod

@multimethod
def foo(x: type[int] | type[float]):
    pass
```
```
TypeError: unbound method type.mro() needs an argument
```

Both worked well with 2.0.2 release. Thanks.

**Comment by coady** [comment]
`foo(Foo())` now correctly raises a `DispatchError`. The issue template has suggestions on how to check types:
```python
assert not issubclass(Foo, subtype(Foo[Any]))
assert issubclass(subtype(Foo[Any]), Foo)
```
